language: r
dist: trusty
sudo: true
os:
- linux
cache: packages
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_05876bcf184d_key -iv $encrypted_05876bcf184d_iv
  -in credentials.enc -out credentials -d
- source credentials
- source <(curl -sSL https://raw.githubusercontent.com/dynverse/travis_scripts/master/helper.sh)
install:
- set -e
- update_docker
- install_hdf5
- install_cran remotes
- install_github_withdeps dynverse/dynwrap dynverse/dyntoy
script:
- source version
- build_docker
- test_docker
after_success:
- push_docker
